### ISSUE TITLE
bt!nh no worky work

### ISSUE THREAD

**Issue by FearrMe** [VTGare/boe-tea-go#1]
https://i.imgur.com/S4RHyLY.png

always links to nh.net/g/0

guessing its this `return 0`
https://github.com/VTGare/boe-tea-go/blob/2b1877f77598a918e1b4ab81086f7563a2d85c65/pkg/nozoki/raw.go#L63-L72

**Comment by VTGare** [comment]
Cringe interface conversion thinks 177013 is float64.
