### ISSUE TITLE
Pixiv artist URL's from sauce command are written out as integers in E notation

### ISSUE THREAD

**Issue by Syampuuh** [VTGare/boe-tea-go#11]
![1625426015](https://user-images.githubusercontent.com/25516124/124396971-82c31d00-dcd2-11eb-9801-7807da52b8ee.png)

![1625426096](https://user-images.githubusercontent.com/25516124/124396972-82c31d00-dcd2-11eb-8246-c309b4ce96ce.png)

This is a weird one.

**Comment by VTGare** [comment]
That's indeed super weird.

**Comment by VTGare** [comment]
Fixed in https://github.com/VTGare/boe-tea-go/commit/dba057ad6b289de23af27a901ca4e64cb413a753
