### ISSUE TITLE
Direct image link/attachments favorite support

### ISSUE THREAD

**Issue by Ryu1845** [VTGare/boe-tea-go#12]
Add support for adding direct image link / attachments to your favorites

**Comment by VTGare** [comment]
This has become even harder to implement after changes made in https://github.com/VTGare/boe-tea-go/commit/4fe03e0e8a5fea358c2cf6c7c3cfaeed2ec450bf. If someone has an idea how to implement this with the current user/artwork/bookmark relation schema, please let me know.

**Comment by Ryu1845** [comment]
What's the problem, actually?

**Comment by VTGare** [comment]
User bookmarks are just references to artworks, they don't contain any data about themselves except an artwork ID and NSFW boolean. See https://github.com/VTGare/boe-tea-go/blob/master/store/bookmarks.go.

**Comment by Ryu1845** [comment]
Not really a fix but if you can change artworkId to str instead of int, you can just store the url

**Comment by Ryu1845** [comment]
Short of that, I don't see any way of doing it and you might as well close the issue imo.

**Comment by VTGare** [comment]
Not feasible, favorites are already clogging up the database as is.

**Comment by Ryu1845** [comment]
OK :+1:
