### ISSUE TITLE
[Bug] Timestamps older than 1 day broken in crosspost footers

### ISSUE THREAD

**Issue by Ghostdesu** [VTGare/boe-tea-go#14]
Any footer timestamp that would include a date contains 01/01/1 instead of a correct date.

**To Reproduce**
1. Set up a crosspost group between any 2 servers.
2. Find an art link on a supported service that is at least 1 day old.
3. Post it in the parent channel of the crosspost group.
4. Observe the issue in a child channel of the group.

**Expected Behavior** 
The footer should contain the accurate date of the post. (e.g. 10/01/2022)

**Screenshots**
![image](https://user-images.githubusercontent.com/31375910/148835735-7c8f0564-1357-489c-bf33-47368c7242fc.png)
![image](https://user-images.githubusercontent.com/31375910/148835762-9fa3261b-40f9-4f0e-a7aa-7d9df6145f8e.png)

**Comment by VTGare** [comment]
Nitter changed timestamp format, so it's failing to parse. This will be fixed when I complete migration to arikawa.

**Comment by VTGare** [comment]
Fixed in https://github.com/VTGare/boe-tea-go/commit/2485753fe9658510fd1c5baede6ba3dc88e55950
