### ISSUE TITLE
Twitter embeds for adult content / content warning

### ISSUE THREAD

**Issue by Dynista** [VTGare/boe-tea-go#15]
Due to a recent change on Twitter, embeds are no longer shown in discord for posts that are marked as adult content (automatically or by content warnings). Twitter requires visitors to log in to see the content.
<img width="648" alt="unknown-42" src="https://user-images.githubusercontent.com/1130392/156648546-6e5f29d9-71f3-4e58-8ba0-73ad84befefd.png">

It would be nice to:
* Have boe tea post the image when an image is marked as adult content, and the channel is marked nsfw (single image tweet)
* Have boe tea post all images when a post is marked as adult content (multi image tweet), currently the first image is skipped for multi image tweets
* maybe a setting to only post on adult content tweets? I personally don't use the Twitter embeds for regular posts, but it would come in handy in this case

**Comment by VTGare** [comment]
Fixed in 3c764991e1af606bd4f8ef2bb938aaedae56c7e4
