### ISSUE TITLE
Use standard logging format

### ISSUE THREAD

**Issue by VTGare** [VTGare/boe-tea-go#24]
To put it bluntly, logging is a bit of a mess right now. Standardize logging everywhere and

- Use standard format for errors and warning that looks like this: `failed to do action: error message`.
- All debug and info level logs should be lowercase.
- Use zap logger features like structured logging.

Example:
```go
func OnMessageRemove(b *bot.Bot) func(*discordgo.Session, *discordgo.MessageDelete) {
	return func(s *discordgo.Session, m *discordgo.MessageDelete) {
		msg, ok := b.EmbedCache.Get(m.ChannelID, m.ID)
                if !ok {
                    return
                }

		log := b.Log.With(
		    "guild_id": m.GuildID,
                    "channel_id": m.ChannelID,
                    "message_id": m.ID,
                    "author_id": msg.AuthorID,
                )

                log.Debug("artwork message was removed, deleting embeds")
                
               // Bunch of other code
       }
}
```

It's okay to add more logs in scope of this issue, but it's not required.

**Comment by Mihai22125** [comment]
Hi @VTGare, can I work on this?

**Comment by VTGare** [comment]
> Hi @VTGare, can I work on this?

Sure, any contributions are welcome. @Mihai22125

**Comment by VTGare** [comment]
I updated the first message to give you an example of how I imagine it to look like. https://github.com/VTGare/boe-tea-go/tree/master/handlers is a good place to start.

**Comment by VTGare** [comment]
Partially covered in 50b838bd0bcc07f59436fcbb4364276900b23f15

**Comment by Mihai22125** [comment]
Hello @VTGare, sorry for the delay. I would still like to contribute on this, so I've started with the handlers package and I raised a new PR for that. Could you review my changes before I move to the remaining packages? Any feedback is more than welcome!
